openapi: 3.0.0
info:
  title: API-Índice-NRG
  version: '1.0'
  description: API para alimentação do Índice Nacional.
  contact:
    name: Welton Nascimento
    email: welton.nascimento@mj.gov.br
servers:
  - url: 'http://localhost:3000'
paths:
  '/Identidades/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        schema:
          type: string
        description: 'Identificador Único da Identidade, composto por um código do estado + o identificador como utilizado pela API-Estadual. {código_estadual}{id}'
    post:
      summary: Incluir uma Identidade
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: O Identificador único que foi incluído
      description: Endpoint de inclusão individual. O ID utilizado pelo estado deve ser precedido de um código estadual.
      operationId: '1'
      security:
        - Chave de Acesso: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Uma Identidade na forma de um objeto Identidade-Sumario
        description: ''
    delete:
      summary: Excluir uma Identidate
      responses:
        '200':
          description: OK
      description: Endpoint de exclusão individual.
      operationId: '2'
      tags: []
  /Identidades:
    post:
      summary: Incluir várias Identidades
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array contendo os Identificadores Únicos que foram aceitos sem erro.
                items:
                  type: string
        '':
          description: ''
          content:
            application/json:
              schema:
                type: array
                description: Um array contendo todos os identificadores que foram incluídos com sucesso.
                items:
                  type: string
      operationId: '3'
      description: |
        Endpoint de inclusão em lotes. O objeto JSON a ser postado deve ter os ID utilizados pelo estado precedidos de um código estadual.

        O Identificador Único da Identidade é composto por um código do estado + o identificador como utilizado pela API-Estadual. {código_estadual}{id}
      security:
        - Chave de Acesso: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: Um Array contendo diversos Identidades como objetos Identidade-Sumario
              items:
                $ref: './api-busca-nacional.v1.yaml#/components/schemas/Identidade-Sumario'
        description: ''
components:
  schemas:
    Identidade-Sumario:
      title: Sumário da Identidade
      type: object
      description: |-
        Sumário ou versão reduzida da identidade para fins de indexação pelo Índice-NRG.

        ## Pendências
        - Necessário definir o tamanho do thumbnail
        - Necessário definir quais dados biográficos (se algum) é obrigatório.
      properties:
        id:
          type: string
          description: ''
        dados_biograficos:
          type: array
          description: Array de Dados Biográficos como especificado na API-Estadual.
          items:
            type: object
        numero:
          type: string
          description: O número que aparece no documento (número do RG)
        data:
          type: string
          format: date
          description: data de expedição do documento
        orgao:
          type: string
          description: Órgão emissor do documento
        thumbnail:
          type: string
          format: uri
          description: 'URI da foto pequena (thumbnail). De preferência esta URI deverá estar acessível diretamento pelo usuário final, de forma que algum mecanismo de URI pré-assinada. Ou seja, essa URI deve ser um request GET acessível sem inclusão de headers de autenticação.'
      required:
        - id
        - dados_biograficos
        - numero
        - data
        - orgao
        - thumbnail
  securitySchemes:
    Chave de Acesso:
      name: XXXXXXXX
      type: apiKey
      in: header
      description: Chave de acesso à API.
