openapi: 3.0.0
info:
  title: API-Índice-NRG
  version: '1.0'
  description: API para alimentação do Índice Nacional.
  contact:
    name: Welton Nascimento
    email: welton.nascimento@mj.gov.br
servers:
  - url: 'http://localhost:3000'
paths:
  '/Identidades/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        schema:
          type: string
        description: 'Identificador Único da Identidade, composto por um código do estado + o identificador como utilizado pela API-Estadual. {código_estadual}{id}'
    post:
      summary: Incluir uma Identidade
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: O Identificador único que foi incluído
      description: Endpoint de inclusão individual. O ID utilizado pelo estado deve ser precedido de um código estadual.
      operationId: '1'
      security:
        - Chave de Acesso: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: './api-estadual.v1.yaml#/components/schemas/Identidade'
        description: ''
    delete:
      summary: Excluir uma Identidate
      responses:
        '200':
          description: OK
      description: Endpoint de exclusão individual.
      operationId: '2'
      tags: []
  /Identidades:
    post:
      summary: Incluir várias Identidades
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array contendo os Identificadores Únicos que foram aceitos sem erro.
                items:
                  type: string
        '':
          description: ''
          content:
            application/json:
              schema:
                type: array
                description: Um array contendo todos os identificadores que foram incluídos com sucesso.
                items:
                  type: string
      operationId: '3'
      description: |
        Endpoint de inclusão em lotes. O objeto JSON a ser postado deve ter os ID utilizados pelo estado precedidos de um código estadual.

        O Identificador Único da Identidade é composto por um código do estado + o identificador como utilizado pela API-Estadual. {código_estadual}{id}
      security:
        - Chave de Acesso: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './api-estadual.v1.yaml#/components/schemas/Identidade'
        description: ''
components:
  schemas: {}
  securitySchemes:
    Chave de Acesso:
      name: XXXXXXXX
      type: apiKey
      in: header
      description: Chave de acesso à API.
